export enum RouterPath {
  PaymentEngine = 'paymentEngine',
  Login = 'login',
  Test = 'test',
  MonitoringStandingOrders = 'monitoringStandingOrders',
  SearchPayment = 'searchPayment',
  BankOpsCheck = 'bankOpsCheck',
  BankOpsDetails = 'bankOpsDetails',
  AntiFraudCheck = 'antiFraudCheck',
  AntiFraudDetails = 'antiFraudDetails',
  AmlCheck = 'amlCheck',
  AmlDetails = 'amlDetails',
  ViewTransferDetails = 'viewTransferDetails',
  ManualChecks = 'manualChecks',
  NotFound = '**',
}
