import { ISearchPayment } from './search-payment.types';

export const searchPaymentMock: ISearchPayment[] = [
  {
    appCreationTime: 'test',
    plannedDate: 'test',
    statusCode: 'test',
    type: 'test',
    paymentSubType: 'test',
    budgetPaymentSubtype: 'test',
    paymentMethod: 'test',
    amount: 'test',
    fee: 'test',
    ownFeeAmount: 'test',
    creditFeeAmount: 'test',
    bonusAmount: 'test',
    bonusRub: 'test',
    loyaltyRate: 'test',
    bonusTypeName: 'test',
    bonusMaxPercent: 'test',
    paymentId: 'test',
    idPH: 'test',
    sourceSystem: 'test',
    bankBIC: 'test',
    serviceName: 'test',
    operatorLegalName: 'test',
    iptID: 'test',
    cifID: 'test',
    applicationID: 'test',
    statusDescriptionPe: 'test',
    parentType: 'test',
    chequeNumber: 'test',
    linkedChequeNumber: 'test',
    linkedChequeId: 'test',
    channelIP: 'test',
    messageToReceiver: 'test',
    sbpTransactionId: 'test',
    sbpWorkflowType: 'test',
    sbpFraudScore: 'test',
    transactionStatus: 'test',
    settlementDate: 'test',
  },
];
