import { IBankOpsCheckResponse } from '../../../../services/bank-ops-check/types';

export const bankOpsCheckTableMock: IBankOpsCheckResponse = {
  count: 10,
  limit: 10,
  offset: 10,
  bankOpsChecks: [
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAML: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
  ],
};
