import { IAmlCheckResponse } from '../../../../services/aml-check/types';

export const amlCheckTableMock: IAmlCheckResponse = {
  count: 10,
  limit: 10,
  offset: 10,
  amlChecks: [
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
    {
      expired: 1,
      paymentId: 'test',
      applicationId: 'test',
      appCreationTime: new Date().toISOString(),
      statusAml: 'test',
      statusAntiFraud: 'test',
      statusBankOps: 'test',
      type: 'test',
      docAmount: 0,
    },
  ],
};
